project_name: pmsg


before:
  hooks:
    - go mod tidy


builds:
  - binary: pmsg

    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/lenye/pmsg/pkg/version.Version={{.Version}}
      - -X github.com/lenye/pmsg/pkg/version.AppName={{.ProjectName}}
      - -X github.com/lenye/pmsg/pkg/version.BuildTime={{.CommitDate}}
      - -X github.com/lenye/pmsg/pkg/version.BuildGit={{.ShortCommit}}
    flags:
      - -trimpath
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
      - 386
      - arm
      - riscv64
      - mips64le
      - ppc64le
      - s390x
    goarm:
      - 7
      - 6
    ignore:
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm
    mod_timestamp: '{{ .CommitTimestamp }}'


archives:
  - id: pmsg
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip


checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_checksums.txt"


changelog:
  filters:
    exclude:
      - '^wip:'
      - '^docs:'
      - '^test:'
      - '^style:'
      - '^chore:'
      - '^ci:'


dockers:
  - image_templates:
      - "ghcr.io/lenye/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "ghcr.io/lenye/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/lenye/{{ .ProjectName }}:latest-amd64"
    dockerfile: Dockerfile
    use: buildx
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.description={{.ProjectName}}"
      - "--label=org.opencontainers.image.url=https://github.com/lenye/{{.ProjectName}}"
      - "--label=org.opencontainers.image.source=https://github.com/lenye/{{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - image_templates:
      - "ghcr.io/lenye/{{ .ProjectName }}:{{ .Tag }}-arm64"
      - "ghcr.io/lenye/{{ .ProjectName }}:{{ .Version }}-arm64"
      - "ghcr.io/lenye/{{ .ProjectName }}:latest-arm64"
    use: buildx
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.description={{.ProjectName}}"
      - "--label=org.opencontainers.image.url=https://github.com/lenye/{{.ProjectName}}"
      - "--label=org.opencontainers.image.source=https://github.com/lenye/{{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - image_templates:
      - "ghcr.io/lenye/{{ .ProjectName }}:{{ .Tag }}-armv6"
      - "ghcr.io/lenye/{{ .ProjectName }}:{{ .Version }}-armv6"
      - "ghcr.io/lenye/{{ .ProjectName }}:latest-armv6"
    use: buildx
    goos: linux
    goarch: arm
    goarm: 6
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm/v6"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.description={{.ProjectName}}"
      - "--label=org.opencontainers.image.url=https://github.com/lenye/{{.ProjectName}}"
      - "--label=org.opencontainers.image.source=https://github.com/lenye/{{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - image_templates:
      - "ghcr.io/lenye/{{ .ProjectName }}:{{ .Tag }}-armv7"
      - "ghcr.io/lenye/{{ .ProjectName }}:{{ .Version }}-armv7"
      - "ghcr.io/lenye/{{ .ProjectName }}:latest-armv7"
    use: buildx
    goos: linux
    goarch: arm
    goarm: 7
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm/v7"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.description={{.ProjectName}}"
      - "--label=org.opencontainers.image.url=https://github.com/lenye/{{.ProjectName}}"
      - "--label=org.opencontainers.image.source=https://github.com/lenye/{{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

docker_manifests:
  - name_template: ghcr.io/lenye/{{ .ProjectName }}:{{ .Tag }}
    image_templates:
      - ghcr.io/lenye/{{ .ProjectName }}:{{ .Tag }}-amd64
      - ghcr.io/lenye/{{ .ProjectName }}:{{ .Tag }}-arm64
      - ghcr.io/lenye/{{ .ProjectName }}:{{ .Tag }}-armv6
      - ghcr.io/lenye/{{ .ProjectName }}:{{ .Tag }}-armv7
  - name_template: ghcr.io/lenye/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/lenye/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/lenye/{{ .ProjectName }}:{{ .Version }}-arm64
      - ghcr.io/lenye/{{ .ProjectName }}:{{ .Version }}-armv6
      - ghcr.io/lenye/{{ .ProjectName }}:{{ .Version }}-armv7
  - name_template: ghcr.io/lenye/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/lenye/{{ .ProjectName }}:latest-amd64
      - ghcr.io/lenye/{{ .ProjectName }}:latest-arm64
      - ghcr.io/lenye/{{ .ProjectName }}:latest-armv6
      - ghcr.io/lenye/{{ .ProjectName }}:latest-armv7