name: Build Binaries with GoReleaser

on:
  push:
    tags:
      - "v*.*.*"      # triggers only if push new tag version, like `v0.1.0`

env:
  GO_VERSION: 1.19

jobs:

  build:
    name: GoReleaser build

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/go/src/github.com/lenye/pmsg

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: go/src/github.com/lenye/pmsg

      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}

      - name: Pull base image
        run: docker pull gcr.io/distroless/static-debian11

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --rm-dist
          workdir: go/src/github.com/lenye/pmsg
        env:
          GITHUB_TOKEN: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}
